"""Utilities for removing archived training artifacts and milestones."""

from __future__ import annotations

import os
from typing import Dict, List


def cleanup_storage(
    archive_dir: str = "archive",
    milestone_dir: str = os.path.join("models", "milestones"),
) -> Dict[str, object]:
    """
    Delete files generated by long-running training sessions.

    Returns:
        Dictionary with delete counts and any errors (non-fatal).
    """
    summary: Dict[str, object] = {
        "archive_deleted": 0,
        "milestones_deleted": 0,
        "errors": [],
    }

    archive_removed, archive_errors = _delete_files_in_dir(archive_dir)
    milestone_removed, milestone_errors = _delete_files_in_dir(
        milestone_dir, suffix=".pth"
    )

    summary["archive_deleted"] = archive_removed
    summary["milestones_deleted"] = milestone_removed
    summary["errors"] = archive_errors + milestone_errors
    return summary


def _delete_files_in_dir(directory: str, suffix: str | None = None) -> tuple[int, List[str]]:
    removed = 0
    errors: List[str] = []

    if not os.path.isdir(directory):
        return removed, errors

    with os.scandir(directory) as entries:
        for entry in entries:
            if not entry.is_file():
                continue
            if suffix and not entry.name.endswith(suffix):
                continue
            try:
                os.remove(entry.path)
                removed += 1
            except OSError as exc:
                errors.append(f"{entry.path}: {exc}")

    return removed, errors

